import torch.nn as nn

'''The FeedForward class implements a fully connected neural network that applies independently and identically to 
each position (token) in a sequence. It is an essential component in Transformers, used to process the representations 
generated by the attention mechanism.'''
class FeedForward(nn.Module):
    def __init__(self, embedding_dimension, feed_forward_dimension):
        super(FeedForward, self).__init__()
        self.linear_layer_1 = nn.Linear(embedding_dimension, feed_forward_dimension)
        self.linear_layer_2 = nn.Linear(feed_forward_dimension, embedding_dimension)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.linear_layer_1(x)
        x = self.relu(x)
        x = self.linear_layer_2(x)
        
        return x