from transformers.vision_transformer import VisionTransformer
from transformers.autoregressive_transformer import AutoregresiveTransformer
from transformers.translator_transformer import TranslatorTransformer